# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TIQuiz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TIQuiz
  pod 'Firebase/Core'
  pod 'Alamofire', '~> 4.8.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

end
